### ISSUE TITLE
Pull request alert types

### ISSUE THREAD

**Issue by eleftherias** [mindersec/minder#5024]
### User Story Description

As a Minder rule author
I want to write a rule that comments on a pull request if there is an evaluation failure
so that I can alert the PR author in the environment they are already using

### Background

We already have existing ruletypes that comment on pull requests (e.g trusty and OSV), but there is nothing in the ruletype definition that explicitly states that commenting will be the action taken if the PR is not compliant.

Furthermore, the logic to comment on a PR is internal to Minder and not available to be reused by external authors of new ruletypes.

### Acceptance Criteria

* Given that I'm a Minder user
   and I've written a rule with the alert type `pull_request_comment`
   and the rule is part of a profile on my project
   when the rule evaluation fails
   then Minder comments on my pull request
* Given I have a rule in a profile with the alert type `pull_request_comment`
   and I've defined the `review_message` in my alert as "This PR has issues"
   then Minder comments on my pull request with the message "This PR has issues"

### Tasks
 - [x] https://github.com/mindersec/minder/issues/5054 
 - [x] https://github.com/mindersec/minder/issues/5117
 - [x] https://github.com/mindersec/minder/issues/5120

**Comment by eleftherias** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Minder-Refinement-66fd8160e83fa80025789d07/issues/mindersec/minder/5024?planning-poker) with Zenhub @blkt @JAORMX

**Comment by eleftherias** [comment]
Closing this as complete. The PR alert type is under the feature flag `pr_comment_alert`.
Here is an example rule definition using the new alert type:
```
def:
  in_entity: pull_request
  param_schema:
    properties: {}
  rule_schema: {}
  ingest:
    type: diff
    diff:
      type: full
  eval:
    type: rego
    rego:
      type: constraints
      violation_format: json
      def: |
        package minder

        import future.keywords.in
        import future.keywords.if

        violations[{"msg": msg}] if {
          # Walk all files in the repo
          files_in_repo := input.ingested.files

          some current_file in files_in_repo
        
          msg := sprintf("File found: %s", [current_file.name])
        }
  alert:
    type: pull_request_comment
    pull_request_comment:
      review_message: |
        {{- range .EvalResultOutput }}  
        - {{ .msg }}
        {{- end }}
```
